/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica3;

import java.awt.*;
import java.io.IOException;

/**
 *
 * @author Esneider
 */
public class Lienzo extends javax.swing.JPanel {

    GrafoLLAdyacencia GrafoLL;
    static int posicionamiento[][];
    /**
     * Creates new form Lienzo
     *
     * @throws java.io.IOException
     */
    public Lienzo() throws IOException {
        initComponents();
        setPreferredSize(new Dimension(600, 600));
        GrafoLL = new GrafoLLAdyacencia();
        //GrafoLLAdyacencia.leerArchivo("C:/Users/Sneid/OneDrive/Escritorio/vertices.txt");

    }

    @Override
    public void paint(Graphics g) {
       super.paint(g); //To change body of generated methods, choose Tools | Templates.

        double rini = 100; // radio inicial 

        //double perimetro =  (3.14 * (2 * rini));
        double posicionx = 0;
        double posiciony = 0;
        double angulo = 360 / (GrafoLLAdyacencia.tamaño()+1);
        double angulocero = 0;
        double radian = Math.toRadians(angulocero);
        double perimetro = (rini * 2 * 3.14 );
        double dtotal = 30 * GrafoLLAdyacencia.tamaño() + 10; 
        while(perimetro < dtotal){
            rini = rini * 2;
            perimetro = (rini * 2 * 3.14 );
        }
        posicionamiento = new int[GrafoLLAdyacencia.tamaño()][2];
       // if (GrafoLL != null) {
            for (int i = 0; i < GrafoLLAdyacencia.tamaño(); i++) {
                posicionx = (Math.cos(radian) * rini);
                posiciony = (Math.sin(radian) * rini);
                posicionamiento[i][0] = (int) posicionx + getWidth() / 2;
                posicionamiento[i][1] = (int) posiciony + getHeight() / 2;

                pintar(g, (((int) posicionx + getWidth() / 2)), ((int) posiciony + getHeight() / 2), GrafoLLAdyacencia.getCabeza(i));
                angulocero = angulocero + angulo;
                radian = Math.toRadians(angulocero);
        //    }
        }
        for (int j = 0; j < GrafoLLAdyacencia.tamaño(); j++) {
            drawnLineas(g, GrafoLLAdyacencia.getCabeza(j));
        }

    }

    public static void pintar(Graphics g, int x, int y, Nodo nodo) {

       if (nodo != null) {
            g.fillOval(x, y, 30, 30);
            g.setColor(Color.red);
            g.drawString(nodo.getNombreVertice(), x + 8, y + 18);
            g.setColor(Color.black);
        }

    }

   
    public void drawnLineas(Graphics g, Nodo cabeza) {

        int x = GrafoLLAdyacencia.verticesNoRepetidos.indexOf(cabeza.getNombreVertice());

        while (cabeza.getLiga() != null) {
            cabeza = cabeza.getLiga();
            int pos = GrafoLLAdyacencia.verticesNoRepetidos.indexOf(cabeza.getNombreVertice());
            g.drawLine(posicionamiento[x][0] + 15, posicionamiento[x][1] + 15, posicionamiento[pos][0] + 15, posicionamiento[pos][1] + 15);
            g.setColor(Color.red);
            g.drawString(Integer.toString(cabeza.getCosto()), (posicionamiento[pos][0] +posicionamiento[x][0] +30)/2, (int)(posicionamiento[pos][1] +posicionamiento[x][1] +30)/2);
            g.setColor(Color.black);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
