/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica3;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;

/**
 *
 * @author user
 */
public class lienzo extends javax.swing.JPanel {

    /**
     * Creates new form lienzo
     */
    public lienzo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setPreferredSize(new java.awt.Dimension(600, 400));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

GrafoLLAdyacencia grafo = new GrafoLLAdyacencia();
Pintar p = new Pintar();
    private final int DIAMETRO = 30;
    private final int ANCHO = 50;
    private final int RADIO = DIAMETRO / 2;
     private final int EXTRA = grafo.nodosCabeza.size()* ANCHO;
     
   
    
    public void Setgrafo(GrafoLLAdyacencia grafo){
        this.grafo = grafo;
        repaint();
    
    }    
   

  
  @Override
    public void paint(Graphics g){
        int x = 20 , y = 20;
    Nodo[] z = new Nodo[grafo.nodosCabeza.size()];
    Nodo Primero = null;
    for(int m = 0; m<=z.length; m++ ){
      Primero = z[m];
    }
    pintar(g, x + 25, y + 25, Primero );
    
    }
    
    
    /*@Override
    public void paint(Graphics g){
        int n = grafo.nodosCabeza.size();
    Nodo[] z = new Nodo[n];
     z = grafo.vertices();
    Nodo Primero ;
   
      Primero = z[0];
   
    p.pintarCirculo(g,  300,  200, Primero );
   
    
    
    }
    */
    public void pintar(Graphics g, int x, int y, Nodo n){
        if(n!= null){
      g.drawOval(x + 25 , y + 25, 20 , 20);
     
      
     }
    
    }
    
   
  
        
    
    
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}

